settings:
  name: "Release Notes"
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
sidebar:
  entries:
    - title: Back to Cloud Manager documentation
      url: https://docs.netapp.com/us-en/cloud-manager-family
    - title: Cloud Manager release notes
      url: /index.html
    - title: Recent changes
      url: /whats-new.html
    - title: Release notes index
      url: /release-notes-index.html
product-family:
  name: Cloud Manager
  repo: cloud-manager-family
homepage:
  tiles:
    - title: What's new
      links:
        - title: Recent changes in Cloud Manager
          url: whats-new.html
    - title: Release notes by service
      links:
        - title: Release notes index
          url: release-notes-index.html
    - title: Blogs & community
      links:
        - title: NetApp Community
          url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
        - title: Cloud Central blog
          url: https://cloud.netapp.com/blog
        - title: Cloud webinars
          url: https://cloud.netapp.com/events
