settings:
  name: "Release Notes"
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"
sidebar:
  entries:
    - title: BlueXP release notes
      url: /index.html
    - title: Recent changes
      url: /whats-new.html
    - title: Release notes index
      url: /release-notes-index.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: BlueXP
  repo: bluexp-family