settings:
  name: "Release Notes"
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
sidebar:
  entries:
    - title: Cloud Manager release notes
      url: /index.html
    - title: Recent changes
      url: /whats-new.html
    - title: Release notes index
      url: /release-notes-index.html

homepage:
  tiles:
    - title: Recent changes
      links:
        - title: What's new in Cloud Manager
          url: whats-new.html
    - title: All release notes
      links:
        - title: Release notes index
          url: release-notes-index.html
    - title: Blogs & community
      links:
        - title: NetApp Community
          url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
        - title: Cloud Central blog
          url: https://cloud.netapp.com/blog
        - title: Cloud webinars
          url: https://cloud.netapp.com/events
